# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1102, 807)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbAnh = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbAnh.setGeometry(QtCore.QRect(280, 30, 551, 251))
        self.lbAnh.setObjectName("lbAnh")
        self.txtChu = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.txtChu.setGeometry(QtCore.QRect(280, 310, 311, 361))
        self.txtChu.setObjectName("txtChu")
        self.layoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(31, 32, 140, 240))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(50)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btChonAnh = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.btChonAnh.setObjectName("btChonAnh")
        self.verticalLayout.addWidget(self.btChonAnh)
        self.btQuetAnhCam = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.btQuetAnhCam.setObjectName("btQuetAnhCam")
        self.verticalLayout.addWidget(self.btQuetAnhCam)
        self.btTrichXuat = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.btTrichXuat.setObjectName("btTrichXuat")
        self.verticalLayout.addWidget(self.btTrichXuat)
        self.btExport = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.btExport.setObjectName("btExport")
        self.verticalLayout.addWidget(self.btExport)
        self.txtChu_2 = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.txtChu_2.setGeometry(QtCore.QRect(640, 310, 311, 361))
        self.txtChu_2.setObjectName("txtChu_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1102, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)


        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbAnh.setText(_translate("MainWindow", "TextLabel"))
        self.btChonAnh.setText(_translate("MainWindow", "Chọn Ảnh"))
        self.btQuetAnhCam.setText(_translate("MainWindow", "Quét Ảnh"))
        self.btTrichXuat.setText(_translate("MainWindow", "Trích Xuất"))
        self.btExport.setText(_translate("MainWindow", "Xuất Excel"))
